---
# tasks file for myrole1
- name: install apache2
  apt:
          name: "{{ deb_package }}"
          state: latest
  when:  ansible_facts['os_family'] == "Debian"
- include_tasks: "restart.yml"
- name: copy index file
  template:
          src: index.j2
          dest: /var/www/html
  notify: restart httpd 

