- name: User Account Managment
  hosts: all
  become: true
  tasks:
          - name: Adding Group
            group: 
                name: simpli
                state: present
          - name: Adding "{{usr1}}"
            user: 
                name: "{{usr1}}"
                state: present
                groups: simpli
                password: "{{ 'password' | password_hash('sha512') }}"
          - name: Adding Software
            apt:
                name: "{{sw}}"
                state: "{{state}}"
